### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'query_selector'

### ISSUE THREAD

**Issue by natv** [danielgross/whatsapp-gpt#1]
Hey thanks for writing these scripts!

I got it mostly installed, up to the point where it tries to launch the browser, but the browser only pops up for a split second and then goes away.

This is the error in the terminal:

┌──(flask)─(kali㉿kali)-[~/whatsapp-gpt/flask]
└─$ python /home/kali/whatsapp-gpt/server.py
Traceback (most recent call last):
  File "/home/kali/whatsapp-gpt/server.py", line 61, in <module>
    start_browser()
  File "/home/kali/whatsapp-gpt/server.py", line 52, in start_browser
    if not is_logged_in():
  File "/home/kali/whatsapp-gpt/server.py", line 25, in is_logged_in
    return get_input_box() is not None
  File "/home/kali/whatsapp-gpt/server.py", line 21, in get_input_box
    return PAGE.query_selector("div[class*='PromptTextarea__TextareaWrapper']").query_selector("textarea")
AttributeError: 'NoneType' object has no attribute 'query_selector'
                                                                                                              

Any help would be appreciated.

**Comment by khandriod** [comment]
same issue with me. how did you fix it
