### ISSUE TITLE
ModuleNotFoundError: No module named 'playwright'

### ISSUE THREAD

**Issue by NikolaVekic** [danielgross/whatsapp-gpt#25]
Installed everything, and was able to launch go run main.go in the env.
When i try to run python3 server.py it always gives me the error:

    from playwright.sync_api import sync_playwright
ModuleNotFoundError: No module named 'playwright'

**Comment by doofzoff** [comment]
pip install playwright

**Comment by waitfortea** [comment]
显示pako未定义怎么办 ，想用execjs执行
